name: nano-reader
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - git
  - pynini=2.1.6.post1
  - pip:
      - -e ./server
      - git+https://github.com/WhizZest/WeTextProcessing.git
